---
# tasks file for ansible-s3cmd-latest

- name: Install python-pip package
  package:
    update_cache=yes
    cache_valid_time=3600
    install_recommends=no
    name=python-pip
    state=present

- name: Install latest s3cmd
  pip:
    name=s3cmd
    state=latest
  ignore_errors: "{{ ansible_check_mode }}"

- name: Symlink s3cmd executable file to /usr/bin
  file:
    src=/usr/local/bin/s3cmd
    dest=/usr/bin/s3cmd
    state=link
    force=yes