---
# tasks file for ansible-s3cmd

- name: Install python packages (Debian)
  package: state=present pkg="{{ item }}" install_recommends=no update_cache=yes cache_valid_time=3600
  when: (ansible_os_family == 'Debian')
  with_items:
    - python-pip
    - python-setuptools
  tags: packages

- name: Install python packages (RedHat)
  package: state=present pkg="{{ item }}" update_cache=yes
  when: (ansible_os_family == 'RedHat')
  with_items:
    - python-pip
    - python-setuptools
  tags: packages

- name: Display s3cmd defined version
  debug: msg="s3cmd_version={{ s3cmd_version }}"

- name: Install s3cmd latest version
  pip:
    name=s3cmd
    state=latest
  when: s3cmd_version == "latest"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install s3cmd defined version
  pip:
    name=s3cmd
    state=present
    version={{ s3cmd_version | default(1.6.1) }}
  when: not s3cmd_version == "latest"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Symlink s3cmd executable file to /usr/bin
  file:
    src=/usr/local/bin/s3cmd
    dest=/usr/bin/s3cmd
    state=link
    force=yes
  when: (ansible_os_family == 'Debian')
